---
name: Gameroom
version: dev
slug: example
description: Game room controller add on for Home Assistant
url: https://github.com/russell-corbett/gameroom
codenotary: russellcorbett11@gmail.com
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
